### ISSUE TITLE
Clear button do not works

### ISSUE THREAD

**Issue by sosnoed** [JTippetts/U3DTerrainEditor#11]
Description: After “Clear” button presses nothing changes, terrain not cleared
  
![image](https://user-images.githubusercontent.com/18216808/43279302-c0ba4302-9137-11e8-8aea-f5fa38771ee0.png)

Repro steps: 
1.	Make some hills on terrain
2.	Press the “Clear” button
Expected: Terrain was cleared
Priority: Medium

**Comment by JTippetts** [comment]
Should be fixed now.
