### ISSUE TITLE
garbage collection in memtest.lua

### ISSUE THREAD

**Issue by stefandd** [JTippetts/U3DTerrainEditor#14]
The garbage collection problem seems to go away if instead of

`function DoThing()
	local c
	for c=1,10000000,1 do
		local c=Color(1,1,1,1)
	end
end
`
one does

`function DoThing()
	local c
	for c=1,10000000,1 do
		local c=Color:new(1,1,1,1)
		c:delete()
	end
end
`
If I replace DoThing() in this way in memtest.lua, it won't allocate large amounts of memory anymore. Wouldn't using :new and :delete heal the issue with the growing garbage collection table ?

**Comment by JTippetts** [comment]
In that particular case it would help, but if you are calling any function inside the loop that returns an Urho type by value (ie, Image::GetPixel or the like) then those generate Lua garbage.

**Comment by stefandd** [comment]
@JTippetts, thanks for the clarification. To my but maybe not your surprise even commercial engine vendor Leadwerks is currently still using toluapp in their current v4 of the engine (see Josh Klint from Leadwerks inquiring about sol2 github: [https://github.com/ThePhD/sol2/issues/613]
