### ISSUE TITLE
MingW(64) build fails with undefined references

### ISSUE THREAD

**Issue by stefandd** [JTippetts/U3DTerrainEditor#15]
The MinGW library libsetupapi.a does not get linked properly when building with MingW/MSYS, leading to an undefined reference error at link time ( undefined reference to `__imp_SetupDiGetClassDevsA' and others).

Proposed small fix to CMakeList.txt is attached.

[CMakeLists.txt](https://github.com/JTippetts/U3DTerrainEditor/files/3617227/CMakeLists.txt)

**Comment by JTippetts** [comment]
Fixed in e92870ae0b4f8338d945c940a16c3e2ee9eaf682
