### ISSUE TITLE
Unable to Build using current Urho3D HEAD library

### ISSUE THREAD

**Issue by Synex** [JTippetts/U3DTerrainEditor#4]
Hi there, I have been having problems trying to build the terrain editor using a Urho3d library build from current HEAD.

When building with Visual Studio 14 I receive the following error:
`Error	C4716	'anl::CKernel::operator=': must return a value	TEdit	c:\users\user\desktop\u3dterraineditor-master\thirdparty\accidental-noise-library\vm\kernel.h	164	
`

I replaced the accidental-noise-library with the latest one committed, but it results in further different errors:

`Error	LNK2019	unresolved external symbol "void __cdecl anl::RegisterANL(class asIScriptEngine *)" (?RegisterANL@anl@@YAXPAVasIScriptEngine@@@Z) referenced in function "void __cdecl LoadScriptBindings(class asIScriptEngine *)" (?LoadScriptBindings@@YAXPAVasIScriptEngine@@@Z)	TEdit	C:\Users\USER\Desktop\U3DTerrainEditor-master\Build\LoadBindings.obj	1	
`

`Error	LNK2019	unresolved external symbol _Direct3DCreate9@4 referenced in function "private: bool __thiscall Urho3D::Graphics::CreateInterface(void)" (?CreateInterface@Graphics@Urho3D@@AAE_NXZ)	TEdit	C:\Users\USER\Desktop\U3DTerrainEditor-master\Build\Urho3D_d.lib(D3D9Graphics.obj)	1	
` 

`Error	LNK2019	unresolved external symbol _D3DCompile@44 referenced in function "private: bool __thiscall Urho3D::ShaderVariation::Compile(void)" (?Compile@ShaderVariation@Urho3D@@AAE_NXZ)	TEdit	C:\Users\USER\Desktop\U3DTerrainEditor-master\Build\Urho3D_d.lib(D3D9ShaderVariation.obj)	1	
`

`Error	LNK1120	3 unresolved externals	TEdit	C:\Users\USER\Desktop\U3DTerrainEditor-master\Build\bin\TEdit_d.exe	1	
`

Furthermore I rebuilt the Urho3d library using OpenGL selected which reduced the error down to:

`Error	LNK2019	unresolved external symbol "void __cdecl anl::RegisterANL(class asIScriptEngine *)" (?RegisterANL@anl@@YAXPAVasIScriptEngine@@@Z) referenced in function "void __cdecl LoadScriptBindings(class asIScriptEngine *)" (?LoadScriptBindings@@YAXPAVasIScriptEngine@@@Z)	TEdit	C:\Users\USER\Desktop\U3DTerrainEditor-master\Build\LoadBindings.obj	1	
`

It is a real shame I cannot get this to work because it seems like such a wonderful tool. Perhaps there are binary files people could download somewhere, or maybe I am missing something obvious?

**Comment by JTippetts** [comment]
Okay, I fixed the original issue. Latest commit should resolve it. I wouldn't recommend replacing with the latest version of the noise library, as that would take a bit more work to fix up some things that have changed in recent commits. If I get a chance, I can do some of that work in the next couple weeks, as it's something I've been meaning to do.
