### ISSUE TITLE
I Really Dont Know How To Use This!

### ISSUE THREAD

**Issue by chenjie199234** [JTippetts/U3DTerrainEditor#5]
What I Can See Is White!!!
White Filled With My Screen With Some UI!
If I Use The Middle Mouse To Rotate My View,I Can See The SkyBox,And White!

The Problem Is Happened On Win10 With Dx11

In U3DTerrainEditor-master\CMake\Modules\UrhoCommon.cmake
It Was Forced To Use DX11 On WinDows Platform.
But In U3DTerrainEditor-master\bin\TerrainEditorData\LuaScripts\terraineditUIoriginal.lua
The TerrainEdit8 Technique Is Called,But There Is No TerrainEdit8.hlsl

It Was OK To Use OPENGL,But It Was Wrong To Use DX11

**Comment by JTippetts** [comment]
I don't have a Windows development machine, so I haven't written the DX11 shaders yet. It's on the TODO list for whenever I have the time to take this project up again, but for now it's GL only.

**Comment by chenjie199234** [comment]
You should modify the \CMake\Modules\UrhoCommon.cmake to force Cmake to use OpenGL
I did this,then it works well on windows with opengl shader!

**Comment by JTippetts** [comment]
The D3D11 shader is in now.
